### ISSUE TITLE
Annotate Schema with optionals/non-optionals

### ISSUE THREAD

**Issue by lightsprint09** [dennispost/1BahnQL#3]
- [x] Station
- [x] Facility
- [x] Parking
- [x] TravelCenter
- [x] Flinkster
- [x] CallABike
- [x] Route

**Comment by dennispost** [comment]
From documentation:

> By default, every type is nullable - it's legitimate to return null as any of the scalar types. Use an exclamation point to indicate a type cannot be nullable, so String! is a non-nullable string.
> To use a list type, surround the type in square brackets, so [Int] is a list of integers.
